### ISSUE TITLE
[Audio] Improve overall sfx both in quality and in coherence 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#105]
We could add variability some events.
Positive actions should have a positive SFX, negative actions a negative SFX: i.e. Sending a Card back (Not Completed / Not Validated) use the same SFX than Completing/Validating them

**Comment by StefanoCecere** [comment]
@CatmanIta can you use 
`SoundManager.I.PlaySfx(AudioEnum.card_positive);`
and
`SoundManager.I.PlaySfx(AudioEnum.card_negative);`

when  cards get completed or disrcarded?
