### ISSUE TITLE
[Assessment] Quitting the questionnaire you should be asked to confirm

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#125]

**Comment by FrancyCavallari** [comment]
Now the confirmation is asked... but the title of the screen is not correct. It should use the text entry **_session_question_assessment_skip_title_**


![Image](https://user-images.githubusercontent.com/17926293/209799308-64de07f5-94c0-40a7-816f-3a7fd1bf46b8.png)

**Comment by CatmanIta** [comment]
This creates a larger bug: this is the same panel that appears during questions. I'd better separate the two
