### ISSUE TITLE
[To Do List] Creating a 2 cards in a row corrupts the UI

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#126]
![image](https://user-images.githubusercontent.com/17926293/206212045-45687e38-030b-445b-82b1-cc66c076e14a.png)

**Comment by FrancyCavallari** [comment]
And if I quit the card creation the first card is deleted insted of the second one

**Comment by CatmanIta** [comment]
I fixed the issue, which was related to scrolling. 
I also fixed the button for creation being always available after you create a second card.

**Comment by FrancyCavallari** [comment]
It's ok now... there's just a minor issue: 
when creating more the one card the text fields are initilized with the text of the previous card
