### ISSUE TITLE
[UI] Country flags are too big, better have all 5 flags fitting in the screen witrhout scrolling

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#127]
![image](https://user-images.githubusercontent.com/17926293/206215810-b941b36f-0d9e-4470-8548-054d57b1247a.png)

**Comment by FrancyCavallari** [comment]
Still present...

**Comment by CatmanIta** [comment]
I noticed it being the case with smaller aspect ratio, I'll change that

**Comment by FrancyCavallari** [comment]
Be careful that I noticed a difference between Simulator and Game view in the editor (maybe it's only the aspect ratio):


![Image](https://user-images.githubusercontent.com/17926293/209800098-842c2b57-54f0-47e2-9d31-ce3bcb1311ae.png)



![Image](https://user-images.githubusercontent.com/17926293/209800145-43fba274-da72-47b4-b0eb-9411f0410619.png)

**Comment by CatmanIta** [comment]
Yes, that is what I was referring to

**Comment by FrancyCavallari** [comment]
I have found/created the following flags... 


![Image](https://user-images.githubusercontent.com/17926293/209881012-eb1cd410-c705-42a8-a729-606177035ef6.png)


but I cannot replace them all because Spanish en German flags are currently JPG (without alpha channel) and I have all PNGs
so those 2 flags appear as before


![Image](https://user-images.githubusercontent.com/17926293/209881118-94c05b87-77c4-47af-bdb1-57b1e66fcf9e.png)
