### ISSUE TITLE
[Language Selections] the list of languages should not be centered

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#129]
the first language should appear on top... right now the element are centered so the first button is not visible
![image](https://user-images.githubusercontent.com/17926293/207602780-53fc71c7-2d54-41bf-8053-7fe48b91e9d7.png)

**Comment by FrancyCavallari** [comment]
The same happens with the Flags for the Host Country
![image](https://user-images.githubusercontent.com/17926293/207603303-df453959-70d8-4634-a161-f68f110e645f.png)

**Comment by CatmanIta** [comment]
Fixed. I also set a fixed layout for flags.
