### ISSUE TITLE
[Assessment] Improve the layout of the category description screen

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#132]
Right now the Title is on the top margin of the screen while the description is in the lower half of the screen
![image](https://user-images.githubusercontent.com/17926293/207606907-aaa283b6-7e99-4ab1-9104-437649a91ad7.png)

It's not very nice...  maybe the description could use a bigger font and be centered between th title and the OK button

**Comment by CatmanIta** [comment]
There was an unapplied edit in the scene, fixed now.

**Comment by FrancyCavallari** [comment]
The layout is much better now... but there's a problem with the size of the category description text:

Up to the third category everything seems fine...
![Image](https://user-images.githubusercontent.com/17926293/209881693-3e71f6cd-d090-4560-a9fd-3423439cfaa6.png)

![Image](https://user-images.githubusercontent.com/17926293/209881765-c836ac02-7165-45a1-9ce3-3c4f802d8671.png)

![Image](https://user-images.githubusercontent.com/17926293/209881792-d9eeacf3-c6c9-4c10-a033-6241a9695b4f.png)

... but then the text becomes very small:

![Image](https://user-images.githubusercontent.com/17926293/209881864-574bead0-85b9-45fc-9a99-bba99a3ada35.png)

![Image](https://user-images.githubusercontent.com/17926293/209881880-60d5eb87-6e82-40db-90e8-7dbc1e20ee5f.png)

![Image](https://user-images.githubusercontent.com/17926293/209881904-7c13c38e-515c-48ac-9709-62b38a969ce8.png)

I suspect it's just a problem with the auto-fit... so maybe better increase the text box for the descriptions and the questions.

**Comment by CatmanIta** [comment]
I made it a bit taller, let me know if it works good for you too
