### ISSUE TITLE
[Tutorial] After the first assessment, I can interact with the pillars but only partially

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#135]
When I'm here...
![image](https://user-images.githubusercontent.com/17926293/207609930-3be1e5b5-c820-449a-8f22-f86779296d51.png)

... I can select a pillar, but then I can only select some other pillars (left or top ones) or go back to the previous/overall view
![image](https://user-images.githubusercontent.com/17926293/207610368-311096ca-6337-44e6-8e10-272f9019e9d8.png)

Either we let the player navigate/view all pillars or we should block any interaction except the suggested one (switch to the To Do List)

**Comment by FrancyCavallari** [comment]
Now the pillar are non-interactive during the tutorial... but the problem of only being able to interact in the left part of the screen is still present when a pillar is selected after the tutorial is over.

**Comment by CatmanIta** [comment]
Regarding that, I would prefer to not let users interact with pillars anymore if no card is on the pillar, as there is no need to do so.
Also, if you *do* have cards on pillars, there is no way to go to another pillar anyway!
 What do you think?

**Comment by CatmanIta** [comment]
Fixed, and I left the interaction as is
