### ISSUE TITLE
[Cards] subcategory può capitare su due righe, spaccando la Ui della carta (deve forzarsi su  una sola riga)

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#137]
![image](https://user-images.githubusercontent.com/17926293/209806986-4fd81dbd-7de8-4b9f-8e7e-a99227677d57.png)

**Comment by CatmanIta** [comment]
I did a pass on the whole card, just to make sure, so that all texts will auto-resize if needed
