### ISSUE TITLE
[2048] End game screen is not coherent with the game itself 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#148]
"Try again" should become "Game Over"
There's no score on screen (nor you can compare your score witht your record)
And the button label should be "Play again" (and it should restart the game)
![image](https://user-images.githubusercontent.com/17926293/210346960-b8157c60-b11f-4927-ab93-1caa3b3d7c01.png)

**Comment by CatmanIta** [comment]
Changed the UI based on type. Note that the game 2048 should handle retrying after the button is pressed like Unblock does
