### ISSUE TITLE
[ToDo List] At first sight, it's not clear how many cards you have in your deck

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#164]
With the new horizontal scolling and intro/exit anims you never see the full deck of cards in the To Do List.
Can you fix/improve it changing the intro/exit anims?
Or should we add a counter in the UI?
Or should ignore it because it's not that important?

**Comment by CatmanIta** [comment]
With the intro animations we had before you could tell if you had "many" or "few" cards, but it created a lot of confusion.
In my opinion, knowing how many cards you have in the "todo" list is not important, as you should focus in order on those that are to be completed.

I would not suggest adding a counter, as the UI is already bloated in that screen. We'd have to place a verbose counter such as "X cards in your TODO list" to make it clear, too. We can fit it on the top-right if needed, however.

**Comment by FrancyCavallari** [comment]
Let's add a simple counter (3/12)
