### ISSUE TITLE
[Activities] Some text are not localized

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#175]
Level (please ignore the "No translation warning"... we still miss that traslation in Arabic and the cell is empty in table)
![image](https://user-images.githubusercontent.com/17926293/216937581-83e285ff-1bb6-4c55-ae4b-0dc72544560c.png)

Score & Best Score
![image](https://user-images.githubusercontent.com/17926293/216938010-0b16aa94-d7af-4fe2-ae02-d6696250b250.png)
![image](https://user-images.githubusercontent.com/17926293/216938308-d8403c48-8b3f-4b59-ab54-e6a048482c0b.png)

**Comment by CatmanIta** [comment]
I went around the activities, and everything seems localized.

I think we need to tie the language however to the localization of the timestamp, as seen in activity or in the cards, as it is wrong to have it be defined by your mobile device.
