### ISSUE TITLE
[Activities] You can "double quit" in the activities and you get stuck 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#182]
In the Writing Activity End Screen, if you click the X in the top-left corner and then confirm that you want to quit... you get back to Activity and you cannot leave it anymore.

Better check all the full-screen popups and hide the top-left X whenever it's not really needed!

**Comment by CatmanIta** [comment]
There is a custom completion logic for this case added by Stefano. I think the abort should be an abort however, so no custom logic should be there to complete the activity.
