### ISSUE TITLE
[UI/UX] review areas that need to be improved before the Pilot Test 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#44]

**Comment by StefanoCecere** [comment]
## generale
engagement: serve _almeno_ una di queste (in ordine di importanza):
- i badges / obiettivi (da sbloccare con score e patterns di comportamento)
- una progression (curva di sviluppo del punteggio e areee)
- comparazione / contest (con altri giocatori.. ma è out of scope)

## UX/UI
- serve transizione tra le 3 aree swipe sul background
- Menù: 
    - Player Profile Panel
    - Settings
    - Informations (qui mettiamo il debug)
- aperta la carta: swipe dx/sx scrolla. swipe giù o una X chiude. un unico pulsante "comando" (o long press) apre il menù di edit o conferma. l'elimina è dentro edit.
- quando confermo una carta: aprire popup di congratulazioni + suono
- il pulsante "completed cards" deve essere parlante
- top e bottom bar: icone troppo grandi, aggiungiamo descrizioni nel bottom, al massimo con l'istant translate
- pillars: non si capisce cosa indicano. mettere sempre in semi trasparenza la categoria
- troppo vuota la scena pillars
- cards: messe di lato e inclinate non è buono. a meno di aprirle e fare la navigazioen al touch
- edit card: non è evidente cosa mosso editare. molto meglio una form indipendente con i 5 campi
- date selector: evidenziare il "+7gg / 1 week". non fare scrolling dei giorni: prima riga i prossimi 7 gg, poi  +2 e + 4 weeks.
- l'exit edit card: se non ho modificato niente non deve chiedere conferma. tendenzialmente i popup di conferma non dovrebbero essere mai necessari.
- risposte SI/NO: mettere sempre il SI a dx (non in verticale) e colorare diversamente i due pulsanti aggiungendo un'icona contestuale
- activity selector: tutta l'area è un pulsante. al click un popup informativo e da lì -> gioco
- create new card button: metterli in alto i pulsanti di azione. in basso c'è già la navigazione
- activities: l'hamburger apre popup (exit, retry, continue)
- serve un'icona per ognuna delle 6 categorie
- app version esplicito (per report)
