### ISSUE TITLE
[Todo List] improve the layout of all cards creation steps

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#54]
**Steps 1 & 2: Category & Sub-Category**
currently it's like this... the card is not really recognizable:
![image](https://user-images.githubusercontent.com/17926293/161822549-694e63af-da9e-40c1-bff4-05953f301a65.png)

Better have the card much smaller:
![image](https://user-images.githubusercontent.com/17926293/161823582-6088a276-8525-40c1-a373-c4ba4713d0fa.png)

**Steps 3, 4, 5: Title, Difficulty, Desc, **
then the card can become slightly bigger when entering the details
![image](https://user-images.githubusercontent.com/17926293/161824435-4f4ade8b-0914-48c3-9ce4-9fd2a9a69274.png)

The same size (a bit smaller) could be used for the single card viewing and editing
![image](https://user-images.githubusercontent.com/17926293/161826242-ad3f35ac-3f3f-4bd4-a1e6-17ff6dd57037.png)

**All Steps**
We should have something highlighting/showing what section are we entering/editing... i.e. 3 empty stars when setting the Difficulty
![image](https://user-images.githubusercontent.com/17926293/161824840-0d52876f-1eb4-4b81-8718-11424c1767e3.png)

**Comment by CatmanIta** [comment]
I also added animated highlights

**Comment by FrancyCavallari** [comment]
It's much better now but it should be further improved...

The blinking rectangle is too flashy, better make the glow fx much slower.

Moreover most of the tooltips are wrongly positioned: 
![image](https://user-images.githubusercontent.com/17926293/162246691-d64b503b-405d-431c-a273-cb20cd1aa1cc.png)

And the text fields should be limited in characters/size or have the text wrapping instead of overflowing
![image](https://user-images.githubusercontent.com/17926293/162247339-a0edca9b-0dcd-4eb7-bbc0-33a04818b55d.png)

**Comment by FrancyCavallari** [comment]
Almost everything is ok.
There are just a couple of details that should be improved...

Title Tooltip is too high, should be positioned closer to the Title itself
![image](https://user-images.githubusercontent.com/17926293/163168254-42505331-2484-494a-9608-b9ddc16916f3.png)

Description highlight should be a bit bigger/wider (and well centered) in order to cover the full text
![image](https://user-images.githubusercontent.com/17926293/163168411-66bf715f-bcaa-431b-8b8d-18066c5e56ba.png)

**Comment by CatmanIta** [comment]
Done
