### ISSUE TITLE
[Todo List] Cards entry animation is broken

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#55]
Only the first card is animated... all others are already positioned and do not move
![image](https://user-images.githubusercontent.com/17926293/161830952-af3092a5-7a96-4cdd-b265-6d69dd9f920d.png)

**Comment by FrancyCavallari** [comment]
Now it correct in the Todo List but it seems to apply the same way also in the Pillars... is it wanted?

**Comment by CatmanIta** [comment]
Not really, just a small error, fixed!
