### ISSUE TITLE
[UI] All rectangle area should be interactive, including the squared icon on the left 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#58]
![image](https://user-images.githubusercontent.com/17926293/161908556-0d9ec799-207f-406d-a1b2-c5fb8309fe57.png)

This is valid for all buttos with an icon on the left

**Comment by CatmanIta** [comment]
I switched the UI up a bit to make this work, as now the whole element is a button. It uses an image on top to simulate the interaction, so it will look a bit different than other buttons
