### ISSUE TITLE
[Assessment] Improve the layout of the intro of the 6 categories... 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#59]
.... currently there are too many colors.
![image](https://user-images.githubusercontent.com/17926293/161908978-ef42602e-1af8-42f1-9a6d-35e555d23be7.png)

**Comment by FrancyCavallari** [comment]
What about simplifying this screen removing the list of categories?
![image](https://user-images.githubusercontent.com/17926293/161944927-08da0259-a9d6-423c-a30f-774293e2003e.png)

**Comment by CatmanIta** [comment]
We need a new key here:
**assessment_intro_content**
