### ISSUE TITLE
[Cards Review] when validating a card the lists do not update well 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#62]
The validated card appear on the Validated list... but it does not disappear from the Completed one.
The Pillares and the list are not animated correctly...

You can also have the pillars labels in a wrong position
![image](https://user-images.githubusercontent.com/17926293/161913379-b1456590-66f4-4e27-82d2-cf7506d5de70.png)

**Comment by CatmanIta** [comment]
Ho sistemato una serie di cose, ma ho notato altre incongruenze. Voglio fare qualche giro prima di segnarlo validato!
