### ISSUE TITLE
[Pillars] In Review mode you cannot set a card as Not Completed

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#65]
![image](https://user-images.githubusercontent.com/17926293/161961695-03d65b78-936c-4014-96a3-fa1d76161ea5.png)
no matter if you are in Session Mode or not.

**Comment by FrancyCavallari** [comment]
Testing a bit more the above bughs seems related to Session Mode...
... but still the behavior of the Un-complete / Un-validate buttons is not correct

In this case I'm asked do set as Not Completed a card that is validated
![image](https://user-images.githubusercontent.com/17926293/161962593-006ab460-533c-468c-9a49-b297ce7e0002.png)

**Comment by CatmanIta** [comment]
Is it what happens here? https://github.com/vgwb/IEEDO/issues/62

**Comment by CatmanIta** [comment]
After completing a card and validating it it works OK for me, maybe it was really the "go back and forth" I signaled in the other issue
