### ISSUE TITLE
[Pillars] In Solo Mode, when browsing the Validated Cards you can set a card as Not Completed

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#73]
Only in Session Mode you can set a card as Validated... but we can allow a Player to set a card as Not Validated when in Solo Mode.
Currently in Solo Mode you can set a card as Not Completed, instead of Not Validated.
![image](https://user-images.githubusercontent.com/17926293/162252923-d15ca63c-eeee-4245-bafb-1af9b0fc8e59.png)

**Comment by FrancyCavallari** [comment]
The problem is present also using the 6-pillars view...
... you can set as Not Completed all cards, no matter if they are Validated or not
![image](https://user-images.githubusercontent.com/17926293/162255840-ec3b3974-d585-4aea-ba40-35739aa8535a.png)

![image](https://user-images.githubusercontent.com/17926293/162255897-0767927a-5b41-47c4-b5dd-d6349c3d00f6.png)

**Comment by FrancyCavallari** [comment]
And it's even worse using the 6-pillars view in Session Mode: you can Validate a Validated card...
![image](https://user-images.githubusercontent.com/17926293/162256432-24b68279-0ef1-48c9-aab8-a7e6661eb743.png)

... and if you do it the card flyes away and falls onto another pillar (on the blue one in this case)...
![image](https://user-images.githubusercontent.com/17926293/162256801-ad01b752-9e99-4a94-87ba-c3e6df026730.png)

... and you can now see a red card among the blue ones !!!
![image](https://user-images.githubusercontent.com/17926293/162256992-1d942dd5-1047-43f8-880f-66054d371335.png)

**Comment by FrancyCavallari** [comment]
if I Calidate a card in the 6-pillars view the card flies to the next pillar (i.e. blue) and then it's part of that category...
in other words https://github.com/vgwb/IEEDO/issues/73#issuecomment-1091983136 is still present

**Comment by CatmanIta** [comment]
Fixed
