### ISSUE TITLE
[Cards] When changing the status of a card, an animation should highlight the change on the card before it flies away

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#74]
When a card is set to Not Completed, Completed or Validated the marker on the top right corner of the card should change status (with a short animation) before the fly away animation starts.

Moreover, in the case of a card marked as Completed, we should also update the date (with a short animation) to today's date before the fly away animation starts. We could also change the background color of the date from White to the card border color (i.e. light blue)

**Comment by FrancyCavallari** [comment]
in fact it's better to only change the background color of the date from White to the card border color (i.e. light blue).... leavbing the date itself unchanged.

**Comment by CatmanIta** [comment]
Done. Not entirely sure about the text being black, tho.

**Comment by FrancyCavallari** [comment]
Ok, let's never use black:
- "card color" text over white background
- white text over "bright card color" background

**Comment by CatmanIta** [comment]
Changed colors
