### ISSUE TITLE
[Minigame] Improve the layout of the Level Completed screen

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#76]
![image](https://user-images.githubusercontent.com/17926293/163120189-f44fe929-e86a-4f70-99a5-103145f8c84b.png)

The whole screen should be improved but for now we can simply rename the Continue button to Play Next Level

**Comment by FrancyCavallari** [comment]
The black Title block should not touch the Top Bar

**Comment by FrancyCavallari** [comment]
Let's use this as a reference
![image](https://user-images.githubusercontent.com/17926293/163152048-165882be-5774-4610-ba9f-7e08cc717920.png)

I added 3 text entries:
play_next_level
activity_result_play_everyday
activity_result_write_everyday

**Comment by CatmanIta** [comment]
It now uses different keys:

- the Game will use
**activity_result_game_win**  **activity_result_game_lose** based on the result as the title
**activity_result_play_everyday** as the content

- the Daily will use
**activity_result_daily_complete** as the title
**activity_result_write_everyday** as the content

**activity_result_title** and **activity_result_score** are instead deprecated
