### ISSUE TITLE
[Card Creation] If you edit a field after completing a card you cannot go back to the deck

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#80]
any click outside is considered as Quit Card Creation
![image](https://user-images.githubusercontent.com/17926293/163157345-7a6dbb82-a679-4b34-a9d7-e7b1cd43abcd.png)

![image](https://user-images.githubusercontent.com/17926293/163157375-fde58b4f-7da3-443f-a087-80e4a1e37b73.png)

**Comment by FrancyCavallari** [comment]
And if you press the Delete button the card is deleted without asking any confirmation

**Comment by CatmanIta** [comment]
After "completing" do you mean after "creating"?
(not happening to me, I'm trying it)

**Comment by CatmanIta** [comment]
Ah, I found it, I misunderstood. It happens the moment you finish the creation

**Comment by FrancyCavallari** [comment]
Yes completing the creation...
... but the issue is still present: I suspect you did not push your fix yet (I don't see any commit related this issue)

**Comment by FrancyCavallari** [comment]
And it's even worse if you switch to the Pillars screen right after completing the cretaion of a card:
switching back to the Todo List the card appears in the deck, but you cannot edit or create any card because the card creation process is still active   
Please check if your fix works also for pressing the Pillars button in the Bottom Bar

**Comment by CatmanIta** [comment]
You are right, I had some pending commits, my bad.
