### ISSUE TITLE
[Delete Card] during the fall down animation the button are still visible & active

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/IEEDO#81]
If you press them you get a warning in the console... 
`MissingReferenceException: The object of type 'UICard' has been destroyed but you are still trying to access it.
`
... better hide them as soon as the animation starts (or even before, when you press the Delete button since the confirmation dialog will appear... but in this case they have to re-appear if the player does not confirm the deletion of the card)

**Comment by CatmanIta** [comment]
I am making sure you cannot click these while the card is being deleted (or any other action is being performed)
